import type { DecisionEvidence } from "./types.ts";

export interface GradeRule extends DecisionEvidence {
  id: string;
  grade: "1" | "2" | "3";
  category: string;
}

const guidelineSection = "붙임 3 변경관리등급 기준" as const;

function rule(id: string, grade: GradeRule["grade"], category: string, description: string): GradeRule {
  return { id, ruleId: id, grade, category, title: description, description, guidelineSection };
}

export const gradeRules: GradeRule[] = [
  rule("G1-DESIGNATED-QUANTITY", "1", "신·증설", "신·증설 Project 중 산업안전보건법 시행령 별표 13 지정수량 이상의 물질을 저장·사용·취급"),
  rule("G1-REACTOR-STRUCTURE", "1", "신·증설", "반응기 등을 신·증설하는 주요 구조부 변경"),
  rule("G1-FLARE-STACK", "1", "신·증설", "Flare Stack 신·증설 주요 구조부 변경"),
  rule("G1-ELECTRICAL-300KW", "1", "신·증설", "전기정격용량 300kW 이상 신·증설 주요 구조부 변경"),
  rule("G1-HEAT-SOURCE", "1", "신·증설", "PSM 대상물질 종류가 변경되지 않고 r값이 1을 넘지 않는 열원 변경"),
  rule("G1-MULTI-EQUIPMENT", "1", "신·증설", "생산량 증가에 따른 다수 설비 증설"),
  rule("G1-UTILITY-EXPANSION", "1", "신·증설", "Boiler, RTO, SRP 등 Utility 설비 증설"),
  rule("G1-ESD", "1", "신·증설", "Plant Emergency Shutdown(ESD) Interlock 변경·삭제·추가"),

  rule("G2-PSM-MATERIAL", "2", "물질 또는 설비", "산업안전보건법 시행령 별표 13 공정안전관리 대상물질 변경(원재료 변경)"),
  rule("G2-PSM-EQUIPMENT", "2", "물질 또는 설비", "공정안전관리 대상물질을 취급하는 설비 변경"),
  rule("G2-FLAMMABLE", "2", "물질 또는 설비", "인화성 가스 또는 인화점 60℃ 이하 인화성 액체로 변경"),
  rule("G2-HIGH-TEMP-PRESSURE", "2", "물질 또는 설비", "인화성 물질·급성독성물질·350℃ 이상 고온·게이지압력 980kPa 이상 고압 조건 또는 해당 설비 변경"),
  rule("G2-PID-EQUIPMENT", "2", "P&ID", "PSM 대상설비 또는 필수 Utility의 장치·설비·동력기계 변경 또는 제거"),
  rule("G2-PID-PIPE", "2", "P&ID", "PSM 대상설비 또는 필수 Utility 배관의 신설·분기·변경·폐기"),
  rule("G2-PID-LOCAL-EXHAUST", "2", "P&ID", "국소배기장치 추가·변경·폐기"),
  rule("G2-PID-CONTROL-VALVE", "2", "P&ID", "Control Valve 신설"),
  rule("G2-PID-ANALYZER", "2", "P&ID", "Analyzer 신설"),
  rule("G2-PID-TRANSMITTER", "2", "P&ID", "Transmitter 신설"),
  rule("G2-PID-ORIFICE", "2", "P&ID", "Orifice Plate 신설"),
  rule("G2-PID-LOGIC", "2", "P&ID", "Interlock Sequence 및 Logic 변경"),
  rule("G2-PID-FAIL-ACTION", "2", "P&ID", "Control Valve Fail Action 변경"),
  rule("G2-PID-OUTSIDE-SPEC", "2", "P&ID", "기존 Spec 범위를 벗어나는 변경"),
  rule("G2-PID-VESSEL", "2", "P&ID", "Vessel·Exchanger·Heater·Tank 용도·재질·구조 변경, 신설 또는 수리"),
  rule("G2-PID-INTERNAL", "2", "P&ID", "용기 내부 Tray·Packing 등 Internal 구조 변경"),
  rule("G2-PID-LINE-ROUTE", "2", "P&ID", "Line Route 변경 또는 신설(지하배관 포함)"),
  rule("G2-PID-SUPPORT", "2", "P&ID", "Line 중량 증가로 Spring Support·Hanger·Expansion Joint 신설이 필요한 배관 변경"),
  rule("G2-ROTATING-PACKING", "2", "회전장치", "왕복압축기 Packing(Ring, Riders) 변경"),
  rule("G2-ROTATING-BEARING", "2", "회전장치", "Bearing Type 변경"),
  rule("G2-ROTATING-SHAFT", "2", "회전장치", "Shaft 또는 Impeller 재질 변경"),
  rule("G2-ROTATING-COMPRESSOR", "2", "회전장치", "원심압축기 부속설비 또는 배관 사양·구조 변경"),
  rule("G2-ROTATING-SEAL", "2", "회전장치", "Seal Type·재질·Size·Piping Plan 개조"),
  rule("G2-ROTATING-LUBE", "2", "회전장치", "윤활유 System 개조"),
  rule("G2-ROTATING-CONDITION", "2", "회전장치", "회전기계 운전조건 또는 용도 변경"),
  rule("G2-ROTATING-TYPE", "2", "회전장치", "회전기계 Type 변경 또는 신규 설치"),
  rule("G2-ROTATING-FOUNDATION", "2", "회전장치", "회전기계 기초 변경"),
  rule("G2-CIVIL-FIRE-SYSTEM", "2", "토목/건축", "건물구조 변경에 전기설비 또는 화재경보시스템 변경이 수반"),
  rule("G2-CIVIL-LAB", "2", "토목/건축", "분석계기를 제외한 실험실 설비 변경"),
  rule("G2-CIVIL-CONTROL-ROOM", "2", "토목/건축", "공정 내 조정실 구조 변경 또는 신설"),
  rule("G2-ELECTRICAL-3_3KV", "2", "전기설비", "3.3kV 이상 전기설비 신설·이설·용량·Model·제작사·Type 변경"),
  rule("G2-ELECTRICAL-PROCESS-POWER", "2", "전기설비", "공정전원계통 변경 또는 신설"),
  rule("G2-ELECTRICAL-EMERGENCY-POWER", "2", "전기설비", "비상전원계통 변경 또는 신설"),
  rule("G2-ELECTRICAL-CONTROL-POWER", "2", "전기설비", "제어전원계통 UPS·Battery Charger 변경 또는 신설"),
  rule("G2-ELECTRICAL-RELAY", "2", "전기설비", "보호계전 System Setting값·Type 변경 또는 신설"),
  rule("G2-ELECTRICAL-EXPLOSION-PROOF", "2", "전기설비", "방폭지역 내 전기설비 밀폐 Type 변경"),
  rule("G2-ELECTRICAL-TIE-IN", "2", "전기설비", "단위공정 수전 전원 Tie-in Point 변경"),
  rule("G2-ESD-SIL", "2", "전기설비", "ESD Sensor·Logic Solver·Final Element 변경으로 안전무결수준(SIL) 변경"),
  rule("G2-SAFETY-DEVICE", "2", "안전장치", "안전밸브·파열판 등 안전방호장치 신규 설치·변경·폐기"),
  rule("G2-ALARM-CONTROL", "2", "안전장치", "경보장치 또는 제어설정값 재설정·변경"),
  rule("G2-OPERATING-PROCEDURE", "2", "운전절차", "정상운전범위를 벗어난 안전운전절차 변경"),

  rule("G3-WORK-STANDARD", "3", "운전절차", "정상운전범위를 벗어나지 않는 작업표준 변경"),
  rule("G3-INSTRUMENT-SPEC", "3", "계측기", "계측기 Maker·Type·Model·Size·Rating·Range 변경"),
  rule("G3-TRANSMITTER-RANGE", "3", "계측기", "Transmitter Range 변경"),
  rule("G3-ORIFICE-REPLACE", "3", "계측기", "Orifice Plate 교체"),
  rule("G3-INSTRUMENT-TYPE-LOCATION", "3", "계측기", "계기 Type 및 위치 단순 변경"),
  rule("G3-CONTROL-VALVE-PART", "3", "계측기", "Control Valve CV값·Trim Type·부품 변경 또는 교체"),
  rule("G3-INSTRUMENT-CABLE", "3", "계측기", "계기관련 Cable 단순 위치 변경 또는 교체"),
  rule("G3-INSTRUMENT-RELOCATION", "3", "계측기", "각종 Instrument 및 Analyzer 이설"),
  rule("G3-PRE-ALARM", "3", "계측기", "각종 Instrument Pre-Alarm Setting값 변경"),
  rule("G3-LIGHTING", "3", "전기설비", "조명설비 신설"),
  rule("G3-COMMUNICATION", "3", "전기설비", "유·무선 통신설비 교체 또는 신설"),
  rule("G3-ELECTRIC-HEAT-TRACING", "3", "전기설비", "Electric Heat Tracing 설치"),
  rule("G3-ELECTRICAL-CABLE", "3", "전기설비", "전기관련 Cable 단순 위치 변경"),
  rule("G3-ELECTRICAL-PANEL", "3", "전기설비", "전기 Panel 교체"),
  rule("G3-DC24", "3", "전기설비", "DC 24V 이하 설비 용량·Model·제작사·Type·보호 Style·Sequence 변경"),
  rule("G3-AC220", "3", "전기설비", "AC 220V 이하 고정설비 신·증설·회로·용량 변경"),
  rule("G3-TEMP-POWER", "3", "전기설비", "3.3kV 미만 임시전원 설치"),
  rule("G3-440V", "3", "전기설비", "440V급 전기설비 신설·증설·이설"),
  rule("G3-DRAIN-VENT", "3", "배관/기계", "Piping System Safety Design에 영향 없는 1 inch 이하 Drain·Vent·Plug Point 추가"),
  rule("G3-STEAM-TRACING", "3", "배관/기계", "기존 배관 Steam Tracing 설치"),
  rule("G3-SIMPLE-SUPPORT", "3", "배관/기계", "설계검토가 필요 없는 단순 Support 설치"),
  rule("G3-REMOVAL", "3", "배관/기계", "설비 또는 배관 철거"),
  rule("G3-SIMPLE-VALVE", "3", "배관/기계", "Block·Bleeder·By-pass Valve 등 단순 Valve 추가"),
  rule("G3-SAMPLING-COOLER", "3", "배관/기계", "Sampling Cooler 설치"),
  rule("G3-EXCHANGER-BUNDLE", "3", "배관/기계", "Exchanger Tube Bundle 교체"),
  rule("G3-STRAINER", "3", "배관/기계", "Cone Type Strainer 추가"),
  rule("G3-MANHOLE", "3", "배관/기계", "Tank 및 압력용기를 제외한 Manhole 설치"),
  rule("G3-INSULATION", "3", "배관/기계", "기존 배관 Insulation 교체 또는 철거"),
  rule("G3-IN-SPEC-PARTS", "3", "배관/기계", "기존 Spec 범위 내 Valve·Gasket·Bolt Type 변경"),
  rule("G3-SIGHT-GLASS", "3", "배관/기계", "기존 배관 Flow Sight Glass 설치"),
  rule("G3-COATING", "3", "배관/기계", "용기 Coating Type 또는 재질 변경"),
  rule("G3-BYPASS-LINE", "3", "배관/기계", "By-pass Line 변경 또는 신설"),
  rule("G3-SAFETY-VALVE", "3", "배관/기계", "Safety Valve 설치"),
  rule("G3-ROTATING-VALVE-LOCATION", "3", "회전장치", "왕복압축기 Cylinder Suction 또는 Discharge Valve 위치 변경"),
  rule("G3-ROTATING-VIBRATION", "3", "회전장치", "진동 및 Bearing 온도 Setting치 변경"),
  rule("G3-ROTATING-COUPLING", "3", "회전장치", "Coupling 설계 변경"),
  rule("G3-ROTATING-LUBE-OIL", "3", "회전장치", "윤활유 종류 변경"),
  rule("G3-ROTATING-ALARM", "3", "회전장치", "회전장치 관련 계기 Alarm·Trip Set 변경"),
  rule("G3-ROTATING-CLEANER", "3", "회전장치", "작업절차에 따른 회전기계 Cleaning Chemical 변경"),
  rule("G3-CIVIL-PARTITION", "3", "토목/건축", "내력벽 구조변경 없는 칸막이 등 건물 단순 구조변경"),
  rule("G3-CIVIL-HVAC-REPLACE", "3", "토목/건축", "기존 건축물 공조설비 교체"),
  rule("G3-CIVIL-FOUNDATION", "3", "토목/건축", "설계검토가 필요한 Foundation 보강"),
  rule("G3-CIVIL-HVAC-NEW", "3", "토목/건축", "공조설비 신설"),
  rule("G3-CIVIL-BUILDING", "3", "토목/건축", "건축물 신설"),
  rule("G3-CIVIL-SIMPLE-STRUCTURE", "3", "토목/건축", "내력벽 구조변경이 없는 단순 구조변경"),
  rule("G3-SAFETY-FIRE-ENV", "3", "안전성 향상", "소방설비·국소배기 제외 환경설비·독성/가연성 가스감지기 변경 또는 추가"),
  rule("G3-SAFETY-CERTIFIED", "3", "안전성 향상", "기존 설비·동력기계·전기·계장기기를 국내안전인증 기기로 교체"),
  rule("G3-SAFETY-GROUND", "3", "안전성 향상", "접지설비 신설·변경·폐기"),
  rule("G3-SAFETY-MATERIAL-AMOUNT", "3", "안전성 향상", "공정 내 취급물질 증감 또는 안전운전지침 개정"),
  rule("G3-SAFETY-IMPROVEMENT", "3", "안전성 향상", "행정기관 점검 조치 등 기타 안전성 향상 개선"),
];
